#!/bin/zsh

# Definición de colores ANSI
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[1;34m'
CYAN='\033[1;36m'
YELLOW='\033[1;33m'
MAGENTA='\033[1;35m'
NC='\033[0m' # No Color
BOLD='\033[1m'

clear

echo ""
echo "${YELLOW}==========================="
echo "A L M I T A   V I R T U A L"
echo "===========================$NC"
echo ""

echo "${CYAN}${BOLD}Descripción General${NC}"
echo "-------------------->"
echo "\"Almita Virtual\" es una App web donde cada usuario puede crear entornos personalizados para presentar o compartir sus documentos importantes, como el Currículum Vitae o carta de presentación."
echo ""
echo "Cada entorno está representado por un personaje \"Almita\" que cambia de estado según la interacción del usuario o visitante. + La propuesta combina solidez técnica con una experiencia estética sensible y simbólica."
echo ""

echo "${CYAN}${BOLD}Usuario y CRUD${NC}"
echo "--------------->"
echo "- El usuario puede crear múltiples entornos (como tener varios Curriculums, o documentos). + Cada Entorno puede contener un archivo."
echo "- Cada entorno incluye:"
echo "  - Título o profesión"
echo "  - Descripción breve"
echo "  - Color personalizado"
echo "  - Archivo adjunto (PDF, JPG O PNG)"
echo "  - Estado"
echo "- CRUD completo de entornos personalizados."
echo "- Eliminando un entorno, se elimina también el archivo del servicio de almacenamiento Cloudinary."
echo ""

echo "${CYAN}${BOLD}Seguridad y Roles${NC}"
echo "------------------>"
echo "- Autenticación con JWT."
echo "- Filtro (middleware) de autorización por roles."
echo "- Roles:"
echo "  - ROLE_USER: solo accede a sus entornos."
echo "  - ROLE_ADMIN: accede a todos los entornos del sistema."
echo ""

echo "${CYAN}${BOLD}Archivos${NC}"
echo "--------->"
echo "- Los usuarios pueden subir y borrar archivos asociados a cada entorno."
echo "- Los visitantes pueden ver y descargar el archivo desde la vista pública del entorno."
echo "- Los archivos se alojan en Cloudinary, solo se guarda el link en la base de datos."
echo ""

echo "${CYAN}${BOLD}Estados de la Almita${NC}"
echo "--------------------->"
echo "- IDLE -> Reposo: sin actividad reciente."
echo "- ACTIVE -> Activo: se sube un archivo."
echo "- REFLECTIVE -> Pensativo: se borra el archivo."
echo "- EXCITED -> Entusiasmado: alguien descarga el archivo."
echo "- INSPIRED -> Inspirado: el usuario pulsa el botón “me interesa”."
echo "Cada estado tiene una animación o video corto representativo, visible en la interfaz del entorno."
echo ""

echo "${CYAN}${BOLD}Diseño Estético${NC}"
echo "---------------->"
echo "- La pantalla muestra:"
echo "  - A la izquierda arriba: la Almita animada."
echo "  - Debajo del Almita: nombre de usuario y los datos del entorno (título, descripción)."
echo "  - Debajo de los datos del Entorno: botones de copiar link y editar Entorno."
echo "  - A la derecha arriba: una pantalla (dibujado)."
echo "  - A la derecha abajo: un teclado (dibujado)."
echo "  - Cada tecla es un botón de acción."
echo "- Adaptable a dispositivos móviles."
echo "- Estética sobria, con base neutra y acentos visuales definidos por la personalización del entorno."
echo ""

echo "${MAGENTA}${BOLD}FLUJO DEL PROGRAMA${NC}"
echo "${MAGENTA}${BOLD}===================${NC}"

echo ""
echo "▶︎ ▶︎ Inicio de la app (User)"
echo ""
echo "Usuario no logueado"
echo "       ${BLUE}↓${NC}"
echo "${YELLOW}➝${NC} Registro (si no tiene cuenta)"
echo "${YELLOW}➝${NC} Login (si ya tiene cuenta)"
echo "       ${BLUE}↓${NC}"
echo "Usuario autenticado con JWT"
echo "       ${BLUE}↓${NC}"
echo "Vista principal del usuario"
echo "       ${BLUE}↓${NC}"
echo "- Ver entornos existentes(se selecciona el entorno desde la lista y entra al mismo)"
echo "- Crear un entorno"
echo "- Editar un entorno (solo dentro del entorno)"
echo "- Eliminar un entorno"
echo "       ${BLUE}↓${NC}"
echo "Vista dentro del entorno"
echo "- Se ve nombre de usuario"
echo "- Se ve título y descripción del entorno (privado, editables por el user)"
echo "- Cambia el estado del entorno automáticamente:"
echo "  - Subir archivo (privado) ${GREEN}          → estado = ACTIVE${NC}"
echo "  - Borrar archivo (privado) ${RED}         → estado = REFLECTIVE${NC}"
echo "  - Descargar/ver archivo (públicos) ${BLUE} → estado = EXCITED${NC}"
echo "  - Me interesa (público) ${MAGENTA}            → estado = INSPIRED${NC}"
echo "       ${BLUE}↓${NC}"
echo "Cerrar sesión"
echo ""

echo "▶︎ ▶︎ Inicio de la app (User_Admin)"
echo ""
echo "Login"
echo "       ${BLUE}↓${NC}"
echo "Usuario autenticado"
echo "       ${BLUE}↓${NC}"
echo "Vista principal del usuario_Admin"
echo "       ${BLUE}↓${NC}"
echo "- Ver todos los entornos(se selecciona el entorno desde la lista y entra al mismo)"
echo "- Crear un entorno"
echo "- Editar un entorno"
echo "- Eliminar un entorno"
echo "       ${BLUE}↓${NC}"
echo "Vista dentro del entorno (misma lógica que User)"
echo "       ${BLUE}↓${NC}"
echo "Cerrar sesión"
echo ""

echo "${MAGENTA}${BOLD}ENDPOINTS NECESARIOS${NC}"
echo "${MAGENTA}${BOLD}=====================${NC}"

echo ""
echo "${BOLD}AUTENTICACIÓN${NC}"
echo -e "${GREEN}POST${NC} /auth/register        → Registrar usuario"
echo -e "${GREEN}POST${NC} /auth/login           → Iniciar sesión (JWT)"
echo ""

echo "${BOLD}ENVIRONMENTS (PRIVADO)${NC}"
echo -e "${BLUE}GET${NC} /environments           → Obtener entornos del usuario"
echo -e "${BLUE}GET${NC} /environments/{id}      → Obtener un entorno por ID"
echo -e "${GREEN}POST${NC} /environments          → Crear un nuevo entorno"
echo -e "${YELLOW}PUT${NC} /environments/{id}      → Editar título, descripción, color o estado"
echo -e "${RED}DELETE${NC} /environments/{id}   → Eliminar un entorno"
echo ""

echo "${BOLD}ARCHIVOS (PRIVADO)${NC}"
echo -e "${GREEN}POST${NC} /environments/{id}/file     → Subir archivo"
echo -e "${RED}DELETE${NC} /environments/{id}/file   → Borrar archivo"
echo ""

echo "${BOLD}ARCHIVOS (PÚBLICO)${NC}"
echo -e "${BLUE}GET${NC} /public/environments/{id}             → Ver entorno"
echo -e "${BLUE}GET${NC} /public/environments/{id}/file        → Ver o descargar archivo"
echo -e "${MAGENTA}PATCH${NC} /public/environments/{id}/status    → Cambiar estado (“me interesa”)"
echo ""

echo "${CYAN}LÓGICA DE NEGOCIO (TREE)${NC}"
echo "${CYAN}===========================${NC}"

echo ""
echo "ALMITA VIRTUAL LOGIC"
echo -e "${YELLOW}│${NC}"
echo -e "${YELLOW}├──${NC} Usuario"
echo -e "│   ├── Se registra con rol por defecto (ROLE_USER)"
echo -e "│   ├── Puede iniciar sesión y recibe JWT"
echo -e "│   └── Ve solo sus entornos"
echo -e "${YELLOW}│${NC}"
echo -e "${YELLOW}├──${NC} Entorno"
echo -e "│   ├── Título obligatorio"
echo -e "│   ├── Descripción opcional (máx. 500 chars)"
echo -e "│   ├── Color elegido (o NEUTRO por defecto)"
echo -e "│   ├── URL de archivo opcional"
echo -e "│   ├── Estado (default: IDLE)"
echo -e "│   └── Relacionado a un único usuario"
echo -e "${YELLOW}│${NC}"
echo -e "${YELLOW}├──${NC} Acciones del entorno"
echo -e "│   ├── Crear / Ver / Editar / Eliminar (privado)"
echo -e "│   ├── Subir archivo → estado = ACTIVE"
echo -e "│   ├── Borrar archivo → estado = REFLECTIVE"
echo -e "│   ├── Descargar o ver archivo → estado = EXCITED"
echo -e "│   ├── Botón “Me interesa” → estado = INSPIRED"
echo -e "│   └── Se crea Entorno sin archivo → estado = IDLE"
echo -e "${YELLOW}│${NC}"
echo -e "${YELLOW}└──${NC} Seguridad"
echo -e "    ├── Registro y login con JWT."
echo -e "    ├── Middleware para rutas privadas."
echo -e "    ├── El User solo puede modificar su entorno."
echo -e "    ├── El Admin puede ver editar y eliminar todos los entornos."
echo -e "    └── Entornos públicos visibles sin login para visitantes con link."

echo ""
echo "${YELLOW}${BOLD}Fin del resumen técnico-narrativo de Almita Virtual.${NC}"
echo ""